<?php

namespace MediaVorus\Media;

require_once dirname(__FILE__) . '/../../../../src/MediaVorus/Media/DefaultMedia.php';

/**
 * Test class for DefaultMedia.
 * Generated by PHPUnit on 2012-03-15 at 10:51:53.
 */
class DefaultMediaTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var DefaultMedia
   */
  protected $object;
  protected $GPSobject;

  protected function setUp()
  {
    $this->object = new DefaultMedia(new \SplFileInfo(__DIR__ . '/../../../files/ExifTool.jpg'), new \PHPExiftool\Exiftool());
    $this->GPSobject = new DefaultMedia(new \SplFileInfo(__DIR__ . '/../../../files/GPS.jpg'), new \PHPExiftool\Exiftool());
  }


  /**
   * @covers \MediaVorus\Media\DefaultMedia::getFile
   */
  public function testGetFile()
  {
    $this->assertInstanceOf('\MediaVorus\File', $this->object->getFile());
    $this->assertEquals('ExifTool.jpg', $this->object->getFile()->getFilename());
  }

  /**
   * @covers \MediaVorus\Media\DefaultMedia::getLongitude
   */
  public function testGetLongitude()
  {
    $this->assertRegExp('/([0-9]+\ deg [0-9]+\'\ [0-9\.]+")/', $this->GPSobject->getLongitude());
  }

  /**
   * @covers \MediaVorus\Media\DefaultMedia::getLongitudeRef
   */
  public function testGetLongitudeRef()
  {
    $this->assertTrue(in_array($this->GPSobject->getLongitudeRef(), array('W','E')));
  }

  /**
   * @covers \MediaVorus\Media\DefaultMedia::getLatitude
   */
  public function testGetLatitude()
  {
    $this->assertRegExp('/([0-9]+\ deg [0-9]+\'\ [0-9\.]+")/', $this->GPSobject->getLatitude());
  }

  /**
   * @covers \MediaVorus\Media\DefaultMedia::getLatitudeRef
   */
  public function testGetLatitudeRef()
  {
    $this->assertTrue(in_array($this->GPSobject->getLatitudeRef(), array('N','S')));
  }

}

