<?php

namespace MediaVorus\Media;

require_once dirname(__FILE__) . '/../../../../src/MediaVorus/Media/DefaultMedia.php';

/**
 * Test class for DefaultMedia.
 * Generated by PHPUnit on 2012-03-15 at 10:51:53.
 */
class DefaultMediaTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var DefaultMedia
   */
  protected $object;

  protected function setUp()
  {
    $this->object = new DefaultMedia(new \SplFileInfo(__DIR__ . '/../../../files/ExifTool.jpg'), new \PHPExiftool\Exiftool());
  }


  /**
   * @covers \MediaVorus\Media\DefaultMedia::getFile
   */
  public function testGetFile()
  {
    $this->assertInstanceOf('\Symfony\Component\HttpFoundation\File\File', $this->object->getFile());
    $this->assertEquals('ExifTool.jpg', $this->object->getFile()->getFilename());
  }

}

